name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth_service, orders_service, warehouse_service, tracking_service, gateway_service]

    steps:
      - uses: actions/checkout@v4

      - name: Build service (no push)
        run: |
          echo "Building ${{ matrix.service }}..."
          docker build ./${{ matrix.service }} -t test/${{ matrix.service }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Dummy deploy
        run: echo "Deploy OK"
